import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync,existsSync}from'node:fs';
import{apps}from'./prepare-footer-candidates.mjs';import{safeRelative,validateManifest,pins,hardenCandidateUnit,assertInactiveUnenabled}from'./apply-footer-candidates.mjs';import{assertProbeIdentity,assertSocketDirectory}from'./footer-candidate-probe.mjs';
import{bindMatrix}from'./footer-bind-check.mjs';
test('payload/dependency manifests pin every file and refuse tampering',{skip:!apps.every(a=>existsSync(`/home/openclaw/ecosystem-footer-build-iZcGAh/${a.slug}-full-manifest.json`))},()=>{for(const app of apps){const file=`/home/openclaw/ecosystem-footer-build-iZcGAh/${app.slug}-full-manifest.json`;const value=JSON.parse(readFileSync(file));assert.equal(validateManifest(value,app),value);assert.ok(value.files.length>300&&value.dependencies.length>20000);assert.ok(value.files.some(([p])=>p==='.next/routes-manifest.json'));assert.ok(value.files.some(([p])=>p==='public/developed-logo.png'));const changed=structuredClone(value);changed.files[0][2]='0'.repeat(64);assert.throws(()=>validateManifest(changed,app));assert.ok(pins[app.slug].old!==app.revision);}});
test('relative artifact paths cannot escape release or name control files outside it',()=>{for(const value of ['../a','a/../b','/etc/passwd','a//b','a\0b','./a'])assert.throws(()=>safeRelative(value));for(const value of ['.next/server/app/login.html','public/developed-logo.png'])assert.doesNotThrow(()=>safeRelative(value));});
test('actual-UID probe rejects root, wrong sibling and unknown slug',()=>{for(const app of apps){assert.doesNotThrow(()=>assertProbeIdentity(app.slug,app.uid,app.gid));assert.throws(()=>assertProbeIdentity(app.slug,0,0));assert.throws(()=>assertProbeIdentity(app.slug,app.uid+1,app.gid));}assert.throws(()=>assertProbeIdentity('other',985,979));});
test('each live phase is exact, journaled and never routes, enables, restarts or deletes old services',()=>{const source=readFileSync(new URL('./apply-footer-candidates.mjs',import.meta.url),'utf8');assert.match(source,/receipt\('bind-attempt'/);assert.match(source,/receipt\(`\$\{app.slug\}-start-attempt`/);assert.match(source,/--hostname 127.0.0.1|noListener\(app.port\)/);assert.doesNotMatch(source,/system\(\['(?:reload|restart|enable|stop)'|unlinkSync|rmSync|nft/);assert.match(source,/verifyCheckpoint\(before\)/);});
test('derived unit preserves staged bytes and appends mandatory directory mask without daemon dependency',()=>{
 const original='[Service]\nInaccessiblePaths=-/run/tailscale -/run/docker.sock\n';const hardened=hardenCandidateUnit(original);assert.ok(hardened.startsWith(original));assert.ok(hardened.endsWith('InaccessiblePaths=/run/tailscale\n'));assert.match(hardened,/After=tailscaled.service/);assert.doesNotMatch(hardened,/(Wants|Requires)=tailscaled/);assert.throws(()=>hardenCandidateUnit(hardened));
});
test('actual socket qualification requires root-owned mode000 directory, not absent/file/optional mask',()=>{
 const stat={uid:0,gid:0,mode:0,isDirectory:()=>true,isSymbolicLink:()=>false};assert.doesNotThrow(()=>assertSocketDirectory(stat));
 for(const changed of[{mode:0o755},{uid:985},{isDirectory:()=>false},{isSymbolicLink:()=>true}])assert.throws(()=>assertSocketDirectory({...stat,...changed}));
 const source=readFileSync(new URL('./footer-candidate-probe.mjs',import.meta.url),'utf8');assert.match(source,/connect\(\{path:'\/run\/tailscale\/tailscaled.sock'\}\)/);assert.match(source,/\['EACCES','EPERM'\]\.includes\(e.code\)/);
});
test('disconnected pre/post bind matrix preserves all old owners and denies new ports to unrelated UIDs',()=>{
 const before={version:1,protectedPorts:[3161,3162,3140],apps:[{name:'vocabulum',uid:985,tcpLoopbackPorts:[3161],udpEphemeral:true},{name:'airsoft',uid:986,tcpLoopbackPorts:[3162],udpEphemeral:true},{name:'central',uid:988,tcpLoopbackPorts:[3140],udpEphemeral:true}]};
 for(const owner of before.apps){const pre=bindMatrix(before,owner.uid,'before'),post=bindMatrix(before,owner.uid,'after');assert.equal(pre[0].allowed,true);assert.deepEqual(post[0],pre[0]);assert.ok(pre.slice(1).every(p=>!p.allowed));for(const item of post.slice(1)){const allowed=item.host==='127.0.0.1'&&((owner.uid===985&&item.port===3171)||(owner.uid===986&&item.port===3172));assert.equal(item.allowed,allowed);}}
});
test('static and disabled candidates qualify only when inactive and without activation dependencies',()=>{
 const state={MainPID:'0',ActiveState:'inactive',UnitFileState:'static',WantedBy:'',RequiredBy:'',TriggeredBy:'',PartOf:''};assert.doesNotThrow(()=>assertInactiveUnenabled(state));assert.doesNotThrow(()=>assertInactiveUnenabled({...state,UnitFileState:'disabled'}));
 for(const change of[{MainPID:'123'},{ActiveState:'active'},{UnitFileState:'enabled'},{WantedBy:'multi-user.target'},{RequiredBy:'other.service'},{TriggeredBy:'example.socket'},{PartOf:'other.service'}])assert.throws(()=>assertInactiveUnenabled({...state,...change}));
 const source=readFileSync(new URL('./apply-footer-candidates.mjs',import.meta.url),'utf8'),body=source.split('function reconcileVocStatic(){')[1].split('\nfunction bind()')[0];assert.ok(body.includes("receipt('vocabulum-installed'"));assert.doesNotMatch(body,/system\(\['(?:start|restart|daemon-reload|enable)'|renameSync|mkdirSync|\blinkSync\(/);
});
